posts:
  - how-to-use-ruby-like-php                        2012-09-08
  - pygments-rb                                     2012-09-11
  - recovering-from-segfaults-in-ruby               2012-11-20
  - changing-the-superclass-of-a-class-in-ruby      2012-12-14
  - why-do-singleton-methods-make-ruby-slow         2012-12-18
  - rails-3.2.10-remote-code-execution              2013-01-10
  - things-that-clear-rubys-method-cache            2013-03-30
code:
  - title: better_errors
    link: https://github.com/charliesome/better_errors
    tags:
      - ruby
    description:
      "A better error page for Rails and other Rack apps. Includes source code inspection, a live REPL and local/instance variable inspection for all stack frames."
  -
    title: eval.in
    link: http://eval.in/
    tags:
      - ruby
      - c
    description:
      "An online code pastebin/evaluator that can execute code written in Ruby, PHP, Python, Lua, IO, Perl and JavaScript."
  -
    title: Slash
    link: https://github.com/slash-lang/slash
    tags:
      - c
    description:
      "A work-in-progress language designed with the goal of being a sane PHP replacement. Ruby object model and semantics, Perl/Ruby-ish syntax, PHP execution model."
  -
    title: Racer
    link: https://github.com/charliesome/racer
    tags:
      - c
    description:
      "A high performance Ruby web server written in C using libuv and node.js's HTTP parser. Faster than Thin, Puma and Unicorn."
  - title: ptydo
    link: https://github.com/charliesome/ptydo
    tags:
      - c
    description:
      "Runs a program in its own pseudo-terminal exposed as stdin/stdout"
  - title: JSOS
    link: https://github.com/charliesome/jsos
    tags:
      - c
      - javascript
      - coffeescript
    description:
      "A JavaScript operating system that uses a simple JavaScript VM I wrote. All drivers and most kernel code is written in JavaScript. The userland is entirely JavaScript and CoffeeScript."
  - title: Twostroke
    link: https://github.com/charliesome/twostroke
    tags:
      - ruby
      - javascript
    description:
      "A JavaScript implementation written in Ruby. Complete enough to run the CoffeeScript compiler and pass all underscore.js tests."
  - title: diffcalc
    link: http://charliesome.github.com/diffcalc
    tags:
      - javascript
    description:
      "A differential calculator written in JavaScript."
talks:
  -
    title: 50 Useful Resources You've Never Heard Of
    link: http://charlie.bz/presos/50resources
    date: 2012
    description:
      "A 5 minute lightning talk I did at the Web Directions \"What do you know?\" night in August."
  - title: Twostroke
    link: http://vimeo.com/36662041
    date: 2012
    description:
      "A talk I gave at MelbJS about Twostroke, my JavaScript implementation in Ruby."
resume:
  work:
    -
      company: Envato
      tenure: 2012 - present
      description:
        Working with Ruby on Rails on the Marketplace team.
    -
      company: Envato
      tenure: 2011 - 2012
      description:
        Working with Ruby and PHP on the Tuts+ Premium team.
  other:
    - title: Ruby on Rails XSS Vulnerability
      subtitle: CVE-2013-1855
      date: 2013
      description:
        "A subtle bug in Rails' sanitize_css method I discovered and reported that allows specially crafted input to inject JavaScript into a page."
    - title: Dragonfly RCE Vulnerability
      subtitle: CVE-2013-1756
      date: 2013
      description:
        "A vulnerability I discovered and reported in the Dragonfly image processing library for Ruby that allows attackers to execute arbitrary Ruby code."
    - title: Ruby on Rails RCE Vulnerability
      subtitle: CVE-2013-0156
      date: 2013
      description:
        "A vulnerability in Rails' parameter parsing that allows attackers to execute arbitrary code I co-discovered and reported."
    - title: Ruby on Rails DoS Vulnerability
      subtitle: CVE-2012-3424
      date: 2012
      description:
        "A denial of service vulnerability in Rails' implementation of digest authentication I discovered and reported."
    - title: MyBB CSRF vulnerability
      date: 2011
      description:
        "A CSRF vulnerability in MyBB's markread functionality."
